name: build-and-deploy-tst

on: push

env:
    AWS_DEFAULT_REGION: us-east-1
    ENVIRONMENT_NAME: tst
    SERVICE_NAME: automation-apis
    AUTOMATION_SAM_BUCKET: automation-sam-deployment

jobs:
    build:
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v2
            - uses: aws-actions/setup-sam@v2
            - uses: actions/setup-node@v3
              with:
                  node-version: 14

            - run: pwd
            - run: ls

            - name: Validate template
              run: sam validate -t template.yml

            - name: Install and compile packages
              run: npm install && npm run compile

            # - name: Run tests
            #   run: npm run cover

            - name: package sam
              run: sam package --s3-bucket "$AUTOMATION_SAM_BUCKET" --s3-prefix "$SERVICE_NAME" --output-template-file ./template.out.yml

            - name: publish sam
              run: sam publish --region "$AWS_DEFAULT_REGION" --template ./template.out.yml

            - name: deploy sam
              run: sam deploy --stack-name "$SERVICE_NAME-$ENVIRONMENT_NAME-$AWS_DEFAULT_REGION" --template-file ./template.out.yml --parameter-overrides "Environment=${ENVIRONMENT_NAME}" --no-fail-on-empty-changeset --capabilities CAPABILITY_IAM CAPABILITY_AUTO_EXPAND